server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/pablo527/Operative_Sistems_final
          search-paths: config-data
    application:
      name: config-server
